# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.7.2
  hooks:
  - id: commitizen
    stages: [ commit-msg ]
- repo: local
  hooks:
  - id: cargo-check
    name: cargo check
    entry: cargo +stable check
    language: system
    pass_filenames: false
  - id: cargo-clippy
    name: cargo clippy
    entry: cargo +nightly clippy -- -D warnings
    language: system
    pass_filenames: false
  - id: cargo-fmt
    name: cargo fmt
    entry: cargo +nightly fmt --check --
    language: system
    types: [ rust ]
  - id: cargo-test
    name: cargo test
    entry: cargo +stable test --workspace
    language: system
    pass_filenames: false
