max_width = 80
tab_spaces = 4
wrap_comments = true
format_strings = true
format_code_in_doc_comments = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
