name: Rust

on:
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish
      run: cargo publish --workspace --token $TOKEN
      env:
        TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
